# Generated by Django 4.2.1 on 2023-06-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0002_album_song"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="formed_in",
        ),
        migrations.RemoveField(
            model_name="band",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="band",
            name="members",
        ),
        migrations.AddField(
            model_name="band",
            name="image",
            field=models.URLField(default=""),
        ),
    ]
