# Generated by Django 4.2.1 on 2023-06-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0005_song_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="band_id",
            field=models.IntegerField(null=True),
        ),
    ]
