# Generated by Django 4.2.1 on 2023-06-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0006_band_band_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="band_id",
        ),
    ]
