# Generated by Django 4.2.2 on 2023-06-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='user_cpf',
            field=models.CharField(default='', max_length=11),
        ),
    ]
